### ISSUE TITLE
Craiglist Scraping

### ISSUE THREAD

**Issue by mihirjham** [sean-connor/roomieup#1]
You could have issues with scraping craigslist. I'd suggest creating seed data rather than trying to scrape craigslist for postings.

**Comment by sean-connor** [comment]
I have started testing with it and can successfully pull down listing information(URLS, Images, Descriptions, Price etc. etc.).  I do think it is too slow to run in real-time requests, but I think I will utilize Heroku schedulers to schedule an hourly job to populate a database with new listings and remove an arbitrarily old amount of information from a database(or frankly, when the 10K Heroku limit is hit).  I will definitely consider seeding, but would like to make an attempt at something that could be utilized as intended.
